<?php

/**
 * @var \Oggetto\Test\Block\Display $block
 */

?>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>

<?php
$_productCollection = $block->getLoadedProductCollection();
?>

<?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
$widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
?>

<?php if ($block->isExpanded()) :?>
    <div class="toolbar-sorter sorter" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
        <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
        <?php echo $block->getSelectHtml(); ?>
    </div>

<?php endif; ?>

<table>
  <tr>
    <th class="post-name">Titile</th>
    <th>Creation Time</th>
    <th>Image</th>
    <th>Description</th>
  </tr>
    <?php
foreach ($block->getNewsCollection() as $key => $post) {
    echo '<tr>
            <td><a href="'.$post->getNewsUrl().'">'.$post->getTitle().'</a></td>
            <td>'.$post->getCreationTime().'</td>
            <td><img width="128" src="'.$post->getImageUrl().'" alt=""></td>
            <td>'.$post->getDescription().'</td>
          </tr>';
}
    ?>
</table>

<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>
